// Automatically generated by diesel
// Creates a module with a submodlue dls, which
// contains functionality used to query/update the
// database.
table! {
    task (id) {
        id -> Integer,
        title -> Text,
        done -> Bool,
    }
}
